#!/bin/sh
# Xsetup - run as root before the login dialog appears
# xrandr to configure sddm for multiple monitors
# consult https://blog.victormendonca.com/2018/06/29/how-to-fix-sddm-on-multiple-screens/ for setup assistance
xrandr --output DisplayPort-0 --auto
xrandr --output DisplayPort-1 --off
